In [1]:
import pandas as pd
from sklearn import tree
from treeviz import tree_print
from sklearn.metrics import accuracy_score

In [2]:
dataset = pd.read_csv('tennis_numeric.csv')

In [3]:
dataset

,outlook_sunny,outlook_overcast,outlook_rainy,temperature,humidity,windy,play
0,1,0,0,85,85,0,no
1,1,0,0,80,90,1,no
2,0,1,0,83,86,0,yes
3,0,0,1,70,96,0,yes
4,0,0,1,68,80,0,yes
5,0,0,1,65,70,1,no
6,0,1,0,64,65,1,yes
7,1,0,0,72,95,0,no
8,1,0,0,69,70,0,yes
9,0,0,1,75,80,0,yes
10,1,0,0,75,70,1,yes
11,0,1,0,72,90,1,yes
12,0,1,0,81,75,0,yes
13,0,0,1,71,91,1,no

In [4]:
treeprint.treeviz.py dataset

SyntaxError: invalid syntax (<ipython-input-4-6b65432148e8>, line 1)